/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultAccountsRouteImport } from './routes/vault/accounts'
import { Route as VaultActivityRouteImport } from './routes/vault/activity'
import { Route as VaultBillsRouteImport } from './routes/vault/bills'
import { Route as VaultCardsRouteImport } from './routes/vault/cards'
import { Route as VaultHelpRouteImport } from './routes/vault/help'
import { Route as VaultMoveRouteImport } from './routes/vault/move'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultAccountsRoute = VaultAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => VaultRoute,
} as any)
const VaultActivityRoute = VaultActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => VaultRoute,
} as any)
const VaultBillsRoute = VaultBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => VaultRoute,
} as any)
const VaultCardsRoute = VaultCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => VaultRoute,
} as any)
const VaultHelpRoute = VaultHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => VaultRoute,
} as any)
const VaultMoveRoute = VaultMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/rates': typeof RatesRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/accounts': typeof VaultAccountsRoute
  '/vault/activity': typeof VaultActivityRoute
  '/vault/bills': typeof VaultBillsRoute
  '/vault/cards': typeof VaultCardsRoute
  '/vault/help': typeof VaultHelpRoute
  '/vault/move': typeof VaultMoveRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/rates': typeof RatesRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/vault/accounts': typeof VaultAccountsRoute
  '/vault/activity': typeof VaultActivityRoute
  '/vault/bills': typeof VaultBillsRoute
  '/vault/cards': typeof VaultCardsRoute
  '/vault/help': typeof VaultHelpRoute
  '/vault/move': typeof VaultMoveRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/rates': typeof RatesRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/accounts': typeof VaultAccountsRoute
  '/vault/activity': typeof VaultActivityRoute
  '/vault/bills': typeof VaultBillsRoute
  '/vault/cards': typeof VaultCardsRoute
  '/vault/help': typeof VaultHelpRoute
  '/vault/move': typeof VaultMoveRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/rates'
    | '/security'
    | '/support'
    | '/vault'
    | '/vault/accounts'
    | '/vault/activity'
    | '/vault/bills'
    | '/vault/cards'
    | '/vault/help'
    | '/vault/move'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/rates'
    | '/security'
    | '/support'
    | '/vault/accounts'
    | '/vault/activity'
    | '/vault/bills'
    | '/vault/cards'
    | '/vault/help'
    | '/vault/move'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/rates'
    | '/security'
    | '/support'
    | '/vault'
    | '/vault/accounts'
    | '/vault/activity'
    | '/vault/bills'
    | '/vault/cards'
    | '/vault/help'
    | '/vault/move'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  RatesRoute: typeof RatesRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/accounts': {
      id: '/vault/accounts'
      path: '/accounts'
      fullPath: '/vault/accounts'
      preLoaderRoute: typeof VaultAccountsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/activity': {
      id: '/vault/activity'
      path: '/activity'
      fullPath: '/vault/activity'
      preLoaderRoute: typeof VaultActivityRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/bills': {
      id: '/vault/bills'
      path: '/bills'
      fullPath: '/vault/bills'
      preLoaderRoute: typeof VaultBillsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/cards': {
      id: '/vault/cards'
      path: '/cards'
      fullPath: '/vault/cards'
      preLoaderRoute: typeof VaultCardsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/help': {
      id: '/vault/help'
      path: '/help'
      fullPath: '/vault/help'
      preLoaderRoute: typeof VaultHelpRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/move': {
      id: '/vault/move'
      path: '/move'
      fullPath: '/vault/move'
      preLoaderRoute: typeof VaultMoveRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultAccountsRoute: typeof VaultAccountsRoute
  VaultActivityRoute: typeof VaultActivityRoute
  VaultBillsRoute: typeof VaultBillsRoute
  VaultCardsRoute: typeof VaultCardsRoute
  VaultHelpRoute: typeof VaultHelpRoute
  VaultMoveRoute: typeof VaultMoveRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultAccountsRoute: VaultAccountsRoute,
  VaultActivityRoute: VaultActivityRoute,
  VaultBillsRoute: VaultBillsRoute,
  VaultCardsRoute: VaultCardsRoute,
  VaultHelpRoute: VaultHelpRoute,
  VaultMoveRoute: VaultMoveRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  RatesRoute: RatesRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
